CREATE TABLE `member` (
  `id` INT(1) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` char(64) NOT NULL,
  `name` varchar(32) DEFAULT NULL,
  `age` INT(1) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;