version: '3'
services:
  application:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      DB_USER: root
      DB_PASSWORD: 1234
      DB_HOST: 127.0.0.1
      DB_PORT: 9501
      DB_NAME: coupons

  coupons_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "9501:3306"
    expose:
      - "9501"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupons
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
