from .controller.entry import entry_router
from .controller.posts import post_router
from .controller.voguekorea import voguekorea_router
from .controller.fashionchingu import fashionchingu_rotuer
from .controller.eyesmag import eyesmag_rotuer
from .controller.fashioninsight import fashioninsight_rotuer
from .controller.unnielooks import unnielooks_router
from .controller.yesstyle import yesstyle_rotuer
from .controller.kmodes import kmodes_rotuer
from .controller.krazefashion import krazefashion_rotuer
from .controller.krazemedia import krazemedia_rotuer
from .controller.harpersbazaar import harpersbazaar_rotuer
