version: '3'
services:
  local_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "9902:3306"
    expose:
      - "9902"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: playground
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci