version: '3'
services:

  legacy_dsp_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "18501:3306"
    expose:
      - "18501"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: legacy_dsp_db
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  legacy_dsp_rabbitmq:
    image: rabbitmq:3.13.0-management
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ruser
      RABBITMQ_DEFAULT_PASS: localpw
      RABBITMQ_DEFAULT_VHOST: legacy
