version: '3'
services:

  legacy_dsp_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "18501:3306"
    expose:
      - "18501"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: legacy_dsp_db
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
