version: '3'
services:

  db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "19501:3306"
    expose:
      - "19501"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: demo
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  proxysql:
    image: proxysql/proxysql:2.1.0
    platform: linux/amd64
    container_name: proxysql
    hostname: proxysql
    ports:
      - "6032:6032"