version: '3'
services:

  petting_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "9100:3306"
    expose:
      - "9100"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pettingdb
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  petting_redis:
    image: redis:latest
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always