version: '3'
services:
  coupons_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "9501:3306"
    expose:
      - "9501"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupons
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci